### ISSUE TITLE
`Error: This contract object doesn't have address set yet, please set an address first.` I believe this error stems from line 13 in batch.js

### ISSUE THREAD

**Issue by ChristianOConnor** [chainstack/ethereum-token-balances#2] opened 2022-03-01 10:37 UTC
When I try to run `node batch.js` this is my output:  
```
<myusername>@<mycomputername> token-balance-through-time % node batch.js
/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-core-helpers/lib/errors.js:122
        return new Error('This contract object doesn\'t have address set yet, please set an address first.');
               ^

Error: This contract object doesn't have address set yet, please set an address first.
    at Object.ContractNoAddressDefinedError (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-core-helpers/lib/errors.js:122:16)
    at Object._processExecuteArguments (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-contract/lib/index.js:728:22)
    at Object._executeMethod (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-contract/lib/index.js:744:68)
    at /Users/<myusername>/Desktop/Dev/token-balance-through-time/batch.js:13:66
    at Array.map (<anonymous>)
    at generateContractFunctionList (/Users/<myusername>/Desktop/Dev/token-balance-through-time/batch.js:10:12)
    at main (/Users/<myusername>/Desktop/Dev/token-balance-through-time/batch.js:22:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
<myusername>@<mycomputername> token-balance-through-time % 
```  

I believe line 13 `batch.add(contract.methods.balanceOf(walletAddress).call.request({}, blockNumber));` is causing the problem because I can get a print to the console of `contract.options.address` when I put a console.log below line 12. What seems to be the problem? I know my urls, credentials, and wallet address are correct?

**Comment by uF4No** [comment] 2022-03-01 12:09
Looks like some tokens have an empty address, which causes some issues. In addition, if there is an issue with some of the requests run in the batch with `await batch.execute()`, it throws an error. I've wrapped this in a try/catch to control the error so the job continues and returns the balances for the remaining tokens.

Change merged to master in https://github.com/chainstack/ethereum-token-balances/pull/4

Let me know if that solves the issue

**Comment by ChristianOConnor** [comment] 2022-03-01 20:09
Thanks for the response and the code fix. Unfortunately, I'm still getting an issue. Here's what appeared in my terminal:  
```
<myusername>@<mycomputername> token-balance-through-time % node batch2.js
tokens retrieved :>>  5146
Error retrieving balances for some tokens
/Users/<myusername>/Desktop/Dev/token-balance-through-time/batch2.js:47
  batchData.response.forEach((res, index) => {
                     ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at main (/Users/<myusername>/Desktop/Dev/token-balance-through-time/batch2.js:47:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
<myusername>@<mycomputername> token-balance-through-time % 
```

**Comment by ChristianOConnor** [comment] 2022-03-01 20:34
I added another try catch to stop the `forEach` error. This is my new `batch.js` file:  
```
const Web3 = require('web3')
const { convertToNumber, getTokens } = require('./utils')
const { abi, bathEndpoint, walletAddress } = require('./constant.js')

const web3 = new Web3(new Web3.providers.HttpProvider(bathEndpoint))

const generateContractFunctionList = ({ tokens, blockNumber }) => {
  const batch = new web3.BatchRequest()

  tokens.map(async ({ address: tokenAddress, symbol, decimals }) => {
    // console.log('tokenAddress :>> ', tokenAddress)
    if (tokenAddress != null && tokenAddress != '') {
      const contract = new web3.eth.Contract(abi)
      contract.options.address = tokenAddress
      try {
        batch.add(
          contract.methods
            .balanceOf(walletAddress)
            .call.request({}, blockNumber)
        )
      } catch (error) {
        console.error('Error adding request to batch for token ', tokenAddress)
      }
    }
  })

  return batch
}

const main = async () => {
  const { tokens } = await getTokens()
  console.log('tokens retrieved :>> ', tokens.length)

  const batch = generateContractFunctionList({ tokens })
  // query block number
  // const batch = generateContractFunctionList({ tokens, blockNumber: 11633038 })
  const tokenBalances = {}
  const tokensIgnored = []
  let batchData
  try {
    batchData = await batch.execute()
  } catch (error) {
    console.error('Error retrieving balances for some tokens')
    batchData = error
  }
  try {
    batchData.response.forEach((res, index) => {
      const { name, decimals, symbol } = tokens[index]
      if (res && res._hex) {
        tokenBalances[name] = `${convertToNumber(res._hex, decimals)} ${symbol}`
      } else {
        tokensIgnored.push(name)
      }
    }) 
  } catch (error) {
    console.error('Error retrieving balances for some tokens')
    batchData = error
  }

  console.log(
    'The following tokens returned an error when checking balance:',
    tokensIgnored
  )
  console.log('----------')
  console.log(
    `Balance checked for ${Object.keys(tokenBalances).length} tokens:`
  )
  console.log(tokenBalances)
}

main()
```


and I got this when I ran it:  
```
<myusername>@<mycomputername> token-balance-through-time % node batch2.js
tokens retrieved :>>  5146
Error retrieving balances for some tokens
Error retrieving balances for some tokens
The following tokens returned an error when checking balance: []
----------
Balance checked for 0 tokens:
{}
/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-abi/lib/index.js:297
        throw new Error('Returned values aren\'t valid, did it run Out of Gas? ' +
              ^

Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.decodeParametersWith (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-abi/lib/index.js:297:15)
    at ABICoder.decodeParameters (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-abi/lib/index.js:284:17)
    at Contract._decodeMethodReturn (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-contract/lib/index.js:493:22)
    at Method.outputFormatter (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-eth-contract/lib/index.js:800:42)
    at Method.formatOutput (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-core-method/lib/index.js:148:54)
    at sendTxCallback (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-core-method/lib/index.js:531:33)
    at /Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-core-requestmanager/lib/index.js:307:9
    at XMLHttpRequest.request.onreadystatechange (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/<myusername>/Desktop/Dev/token-balance-through-time/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
<myusername>@<mycomputername> token-balance-through-time % 
```

**Comment by uF4No** [comment] 2022-03-02 09:35
I've been able to replicate the following error by setting an invalid wallet address or invalid endpoints in the `constant.js` file. 
Please make sure that you configure these before running the script. You can find more info about how to obtain your node credentials and endpoint [in this section of the docs](https://docs.chainstack.com/platform/view-node-access-and-credentials#public-chain-nodes/)

**Comment by ChristianOConnor** [comment] 2022-03-03 01:31
I am positive my node is working correctly and my credentials are fine. I ran this code and it worked perfectly:  
```
const Web3 = require('web3')
const {bathEndpoint} = require('./constant.js')

const web3 = new Web3(new Web3.providers.HttpProvider(bathEndpoint))

web3.eth.getBlockNumber().then(console.log);
```  

And I got this `14311027` so clearly my node is working. I will show you the EXACT code below and it isn't working even though i have the Business Tier Archival Node running Geth with correct credentials.  

constant.js (process.env.BLOCK_NUMBER is 12155258)  
```
// Get the following from your Chainstack console
// Check https://docs.chainstack.com/platform/view-node-access-and-credentials#public-chain-nodes
require('dotenv').config()

const username = process.env.USERNAME // replace with your Ethereum node RPC username
const password = process.env.PASSWORD // replace with your Ethereum node RPC password
const rpcEndpoint = 'https://' + process.env.PASSWORD_PROTECTED_ENDPOINT // replace with your Ethereum node RPC endpoint
const rpcNoHttpPart = process.env.PASSWORD_PROTECTED_ENDPOINT
const bathEndpoint = `https://${username}:${password}@${rpcNoHttpPart}` // replace with your Ethereum node RPC endpoint
// replace with the address you want to query
const walletAddress = process.env.USER_ADDRESS
const blockNumber = process.env.BLOCK_NUMBER

const abi = [
  {
    constant: true,
    inputs: [
      {
        name: '_owner',
        type: 'address',
      },
    ],
    name: 'balanceOf',
    outputs: [
      {
        name: 'balance',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
]

module.exports = {
  abi,
  bathEndpoint,
  password,
  rpcEndpoint,
  username,
  walletAddress,
  blockNumber
}
```  

utils.js  
```
const { toBN } = require('web3-utils');
require('isomorphic-fetch');

const tokenSource = 'https://tokens.coingecko.com/uniswap/all.json';
const getTokens = () => {
  return fetch(tokenSource, {
    methods: 'GET',
    headers: { 'Content-Type': 'application/json', },
  }).then(data => data.json());
};

const convertToNumber = (hex, decimals) => {
  const balance = toBN(hex);
  let balanceDecimal = balance;
  if (decimals && (balance.toLocaleString() === '0' && decimals < 20)) {
    balanceDecimal = balance.div(toBN(10 ** decimals));
  }

  return balanceDecimal.toLocaleString();
};

module.exports = {
  convertToNumber,
  getTokens,
};
```  

batch.js  
```
const Web3 = require('web3')
const fs = require('fs')
const { convertToNumber, getTokens } = require('./utils')
const { abi, bathEndpoint, walletAddress, blockNumber } = require('./constant.js')

const web3 = new Web3(new Web3.providers.HttpProvider(bathEndpoint))

const generateContractFunctionList = ({ tokens, blockNumber }) => {
  const batch = new web3.BatchRequest()

  tokens.map(async ({ address: tokenAddress, symbol, decimals }) => {
    // console.log('tokenAddress :>> ', tokenAddress)
    if (tokenAddress != null && tokenAddress != '') {
      const contract = new web3.eth.Contract(abi)
      contract.options.address = tokenAddress
      try {
        batch.add(
          contract.methods
            .balanceOf(walletAddress)
            .call.request({}, blockNumber)
        )
      } catch (error) {
        console.error('Error adding request to batch for token ', tokenAddress)
      }
    }
  })

  return batch
}

const main = async () => {
  //const { tokens } = await getTokens()
  const tokens = JSON.parse(fs.readFileSync('./tokenArrayFormatted1.json'));

  console.log('tokens retrieved :>> ', tokens.length)

  // const batch = generateContractFunctionList({ tokens })
  // query block number
  const batch = generateContractFunctionList({ tokens, blockNumber: blockNumber })
  const tokenBalances = {}
  const tokensIgnored = []
  let batchData
  try {
    batchData = await batch.execute()
  } catch (error) {
    console.error('Error retrieving balances for some tokens')
    batchData = error
  }

  try {
    batchData.response.forEach((res, index) => {
      const { name, decimals, symbol } = tokens[index]
      if (res && res._hex) {
        tokenBalances[name] = `${convertToNumber(res._hex, decimals)} ${symbol}`
      } else {
        tokensIgnored.push(name)
      }
    }) 
  } catch (error) {
    console.error('Error retrieving balances for some tokens')
    batchData = error
  }

  console.log(
    'The following tokens returned an error when checking balance:',
    tokensIgnored
  )
  console.log('----------')
  console.log(
    `Balance checked for ${Object.keys(tokenBalances).length} tokens:`
  )
  console.log(tokenBalances)
}

main()
```  

This is my pre-organized list of token set up perfectly to work with the script (tokenArrayFormatted1.json).  
```
[
    {
        "chainId": 1,
        "address": "0xf3AE5d769e153Ef72b4e3591aC004E89F48107a1",
        "name": "Deeper Network",
        "symbol": "DPR",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xf680429328caaaCabee69b7A9FdB21a71419c063",
        "name": "Butterfly Protocol Governance Token",
        "symbol": "BFLY",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x8B39B70E39Aa811b69365398e0aACe9bee238AEb",
        "name": "PolkaFoundry",
        "symbol": "PKF",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xa8c8CfB141A3bB59FEA1E2ea6B79b5ECBCD7b6ca",
        "name": "NOIA Token",
        "symbol": "NOIA",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x57B946008913B82E4dF85f501cbAeD910e58D26C",
        "name": "Marlin POND",
        "symbol": "POND",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x362bc847A3a9637d3af6624EeC853618a43ed7D2",
        "name": "Parsiq Token",
        "symbol": "PRQ",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x77FbA179C79De5B7653F68b5039Af940AdA60ce0",
        "name": "Ampleforth Governance",
        "symbol": "FORTH",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x40FD72257597aA14C7231A7B1aaa29Fce868F677",
        "name": "Sora Token",
        "symbol": "XOR",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x6fC13EACE26590B80cCCAB1ba5d51890577D83B2",
        "name": "Umbrella",
        "symbol": "UMB",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x67B6D479c7bB412C54e03dCA8E1Bc6740ce6b99C",
        "name": "Kylin Network",
        "symbol": "KYL",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xf4CD3d3Fda8d7Fd6C5a500203e38640A70Bf9577",
        "name": "YfDAI.finance",
        "symbol": "Yf-DAI",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x8eEF5a82E6Aa222a60F009ac18c24EE12dBf4b41",
        "name": "Tixl Token",
        "symbol": "TXL",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x0391D2021f89DC339F60Fff84546EA23E337750f",
        "name": "BarnBridge Governance Token",
        "symbol": "BARN",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "name": "USD Coin",
        "symbol": "USDC",
        "decimals": 6
    },
    {
        "chainId": 1,
        "address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
        "name": "Uniswap",
        "symbol": "UNI",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20",
        "name": "DuckDaoDime",
        "symbol": "DDIM",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xC0bA369c8Db6eB3924965e5c4FD0b4C1B91e305F",
        "name": "DLP Duck Token",
        "symbol": "DLP",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x9469D013805bFfB7D3DEBe5E7839237e535ec483",
        "name": "Darwinia Network Native Token",
        "symbol": "RING",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x27702a26126e0B3702af63Ee09aC4d1A084EF628",
        "name": "aleph.im v2",
        "symbol": "ALEPH",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0xe28b3B32B6c345A34Ff64674606124Dd5Aceca30",
        "name": "Injective Token",
        "symbol": "INJ",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x07baC35846e5eD502aA91AdF6A9e7aA210F2DcbE",
        "name": "erowan",
        "symbol": "EROWAN",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",
        "name": "Matic Token",
        "symbol": "MATIC",
        "decimals": 18
    },
    {
        "chainId": 1,
        "address": "0x95a4492F028aa1fd432Ea71146b433E7B4446611",
        "name": "APY Governance Token",
        "symbol": "APY",
        "decimals": 18
    }
]
```  
  
And finally this is my FAILED output.  
```
<myusername>@<mycomputername> token-balance-through-time % node batch.js 
tokens retrieved :>>  23
Error retrieving balances for some tokens
The following tokens returned an error when checking balance: []
----------
Balance checked for 0 tokens:
{}
<myusername>@<mycomputername> token-balance-through-time %
```  

So what's the problem?? I have the business tier geth archival node so I know that the functionality is available to me?

**Comment by uF4No** [comment] 2022-03-03 11:58
I've copied your code into new files (batch2.js and constant2.js), installed `dotenv`, created an env file, and configured the endpoints, credentials, and a valid wallet address. I've also used the token list and block number provided above. 

Here is my output:

```
node batch2.js 
tokens retrieved :>>  23
The following tokens returned an error when checking balance: []
----------
Balance checked for 23 tokens:
{
  'Deeper Network': '0 DPR',
  'Butterfly Protocol Governance Token': '0 BFLY',
  PolkaFoundry: '0 PKF',
  'NOIA Token': '0 NOIA',
  'Marlin POND': '0 POND',
  'Parsiq Token': '0 PRQ',
  'Ampleforth Governance': '0 FORTH',
  'Sora Token': '0 XOR',
  Umbrella: '0 UMB',
  'Kylin Network': '0 KYL',
  'YfDAI.finance': '0 Yf-DAI',
  'Tixl Token': '0 TXL',
  'BarnBridge Governance Token': '0 BARN',
  'USD Coin': '0 USDC',
  Uniswap: '0 UNI',
  DuckDaoDime: '0 DDIM',
  'DLP Duck Token': '0 DLP',
  'Darwinia Network Native Token': '0 RING',
  'aleph.im v2': '0 ALEPH',
  'Injective Token': '0 INJ',
  erowan: '0 EROWAN',
  'Matic Token': '0 MATIC',
  'APY Governance Token': '0 APY'
}
```

I've created [a new branch](https://github.com/chainstack/ethereum-token-balances/tree/issues/2) that you can try to run. I've included a console.log to print the actual error so if it's still failing we should at least get more information about why.

I've also tested with an invalid wallet address and, in that's the case, you'll the see following error for all tokens:

```
Error adding request to batch for token  0xFbEEa1C75E4c4465CB2FCCc9c6d6afe984558E20
```

**Comment by ChristianOConnor** [comment] 2022-03-03 19:33
Still not working...  
```
<myusername>@<mycomputername> token-balance-through-time % node batch2.js
bathEndpoint :>>  CENSORED
tokens retrieved :>>  23
batch :>>  Batch {
  requestManager: RequestManager {
    provider: HttpProvider {
      withCredentials: false,
      timeout: 0,
      headers: undefined,
      agent: undefined,
      connected: false,
      host: CENSORED,
      httpsAgent: [Agent]
    },
    providers: {
      WebsocketProvider: [Function: WebsocketProvider],
      HttpProvider: [Function: HttpProvider],
      IpcProvider: [Function: IpcProvider]
    },
    subscriptions: Map(0) {}
  },
  requests: [
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    },
    {
      params: [Array],
      callback: undefined,
      method: 'eth_call',
      format: [Function: bound ]
    }
  ]
}
Error retrieving balances for some tokens
The following tokens returned an error when checking balance: []
----------
Balance checked for 0 tokens:
{}
<myusername>@<mycomputername> token-balance-through-time % 
```  
  
Are you an employee at Chainstack? Can I private message you my entire project file including credentials so you can run my exact code and see what the problem is?  

Also weirdly enough the etherplex.js file does work for me when I run it lol. Only trouble is that there is no way to input `blockNumber`. Is there any way to get the balances with the etherplex.js file at a particular block number?

**Comment by uF4No** [comment] 2022-03-04 10:12
Yes, I'm a developer advocate at Chainstack. Let's fix this 

You can send me a message [in our discord channel](https://discord.gg/Cymtg2f7pX) and we can move on from there.

**Comment by uF4No** [comment] 2022-03-11 09:35
Closing this issue as the original problem was caused by using a different version of web3.js. The code of the tutorial only works with v2.0.0-alpha.1. Newer versions require a callback function to be included as the last parameter to `batch.add()`.

We'll release an updated article using the latest web3 version.

**Closed by uF4No** 2022-03-11 09:35 UTC
